class CreateGrapes < ActiveRecord::Migration
  def up
    create_table :grapes do |t|
      t.string :name

      t.timestamps
    end

    Grape.create :name => 'Alfrocheiro'
    Grape.create :name => 'Agiorgitiko'
    Grape.create :name => 'Aglianico'
    Grape.create :name => 'Almansa'
    Grape.create :name => 'Amarone'
    Grape.create :name => 'Baco Noir'
    Grape.create :name => 'Baga'
    Grape.create :name => 'Barbaresco'
    Grape.create :name => 'Barbera'
    Grape.create :name => 'Barolo'
    Grape.create :name => 'Braucol'
    Grape.create :name => 'Cabernet Franc'
    Grape.create :name => 'Cabernet Sauvignon'
    Grape.create :name => 'Carmenere'
    Grape.create :name =>  'Carignan'
    Grape.create :name =>  'Cava'
    Grape.create :name =>  'Corvina'
    Grape.create :name =>  'Cinsault'
    Grape.create :name =>  'Dolcetto'
    Grape.create :name =>  'Gamay'
    Grape.create :name =>  'Grenache'
    Grape.create :name =>  'Grenache Noir'
    Grape.create :name =>  'Foch'
    Grape.create :name =>  'Lacrima'
    Grape.create :name =>  'Malbec'
    Grape.create :name =>  'Mencia'
    Grape.create :name =>  'Merlot'
    Grape.create :name =>  'Montepulciano'
    Grape.create :name =>  'Mourvedre'
    Grape.create :name =>  'Nebbiolo'
    Grape.create :name =>  'Nero d\'Avola'
    Grape.create :name =>  'Nero di Troia'
    Grape.create :name =>  'Negroamaro'
    Grape.create :name =>  'Perricone'
    Grape.create :name =>  'Petit Verdot'
    Grape.create :name =>  'Petite Syrah'
    Grape.create :name =>  'Pinot Noir'
    Grape.create :name =>  'Pinotage'
    Grape.create :name =>  'Primitivo'
    Grape.create :name =>  'Prosecco'
    Grape.create :name =>  'Raboso'
    Grape.create :name =>  'Red Blend'
    Grape.create :name =>  'Rondinella'
    Grape.create :name =>  'Saperavi'
    Grape.create :name =>  'Sangiovese'
    Grape.create :name =>  'Syrah'
    Grape.create :name =>  'Tempranillo'
    Grape.create :name =>  'Tinta Roriz'
    Grape.create :name =>  'Touriga Franca'
    Grape.create :name =>  'Touriga Nacional'
    Grape.create :name =>  'Trincadeira'
    Grape.create :name =>  'Zinfandel'
    Grape.create :name =>  'Zweigelt'
    Grape.create :name =>  'Other Red'
    Grape.create :name =>  'Albarino'
    Grape.create :name =>  'Altesse'
    Grape.create :name =>  'Aligote'
    Grape.create :name =>  'Bonarda'
    Grape.create :name =>  'Chardonnay'
    Grape.create :name =>  'Chasselas'
    Grape.create :name =>  'Chenin Blanc'
    Grape.create :name =>  'Garganega'
    Grape.create :name =>  'Grenache Blanc'
    Grape.create :name =>  'Gewurztraminer'
    Grape.create :name =>  'Gruner Veltliner'
    Grape.create :name =>  'Inzolia'
    Grape.create :name =>  'Malvasia'
    Grape.create :name =>  'Muscat'
    Grape.create :name =>  'Pecorino'
    Grape.create :name =>  'Nuragus'
    Grape.create :name =>  'Pinot Blanc'
    Grape.create :name =>  'Pinot Grigio'
    Grape.create :name =>  'Riesling'
    Grape.create :name =>  'Sauvignon Blanc'
    Grape.create :name =>  'Other White'
    Grape.create :name =>  'Rizling'
    Grape.create :name =>  'Roussanne'
    Grape.create :name =>  'Semillon'
    Grape.create :name =>  'Soave'
    Grape.create :name =>  'Torrontes'
    Grape.create :name =>  'Vidal'
    Grape.create :name =>  'Viognier'
    Grape.create :name =>  'Viura'
    Grape.create :name =>  'Viuria'
    Grape.create :name =>  'Verdejo'
    Grape.create :name =>  'Vernaccia'
    Grape.create :name =>  'Vermentino'
    Grape.create :name =>  'White Blend'

  end

  def down
    drop_table :grapes
  end
end
